import axios from 'axios'

export const GET_PLAYER_DATA_START = 'GET_PLAYER_DATA_START'
export const GET_PLAYER_DATA_SUCCESS = 'GET_PLAYER_DATA_SUCCESS'
export const  GET_PLAYER_DATA_FAILURE = 'GET_PLAYER_DATA_FAILURE' 